### ISSUE TITLE
Getting an Error when I run scripts/run.sh

### ISSUE THREAD

**Issue by The-ultra** [tqbl/dcase2020_task5#2]
I was trying to run  `scrips/run.sh` through bash, I downloaded all the requirements as stated in the readme file, I don't know what I should do or what I did wrong 
Note: this was the 2nd time running it cause electricity died out before I took a screenshot(I don't have a supercomputer), It gave the same error as the first time

![updated_LI](https://user-images.githubusercontent.com/40963403/159257716-044715dc-d41b-4d92-903b-32ab714ee85a.jpg)

**Comment by tqbl** [comment]
Sorry about the late reply. I think the quickest way to resolve this is to first check what `df[key]` and `value` are just before [this line](https://github.com/tqbl/dcase2020_task5/blob/master/task5/core/mask.py#L18). `df[key]` should be a Series of integers and `value` should be an integer. If that's not the case (the error suggests it's not), we can go from there. Let me know what the output is for these two values.

Suggestion: add `pdb.set_trace()` just before that line so you can debug interactively (remember to import pdb).

More generally, did you install the exact same dependency versions? Sometimes, newer package versions introduce breaking changes.

**Comment by The-ultra** [comment]
Hey so I think I know where the problem is so, when I try to install torch=1.4.0 using dependencies whether through
 `pip install -r requirements.txt` or the ` poetry install` I get this Error
![poetry fail](https://user-images.githubusercontent.com/40963403/159919360-85bf2459-8dc7-467d-82b9-6800790f234c.PNG)
I have tried downloading it on Cuda 10.1 and 11.1 and both give the same Error




the previous Error is caused as you mentioned in your reply is caused when I download the current version of pytorch through
`conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch`

after using ` conda install pytorch==1.4.0 torchvision==0.5.0 cudatoolkit=10.1 -c pytorch` I get the same error
![woeee](https://user-images.githubusercontent.com/40963403/159929800-878008df-6c27-406d-b09a-e4cefe18c1d3.PNG)



I will now go and try the earlier approach you mentioned

**Comment by The-ultra** [comment]
I have done your approach but I am not sure what it means tbh
![image](https://user-images.githubusercontent.com/40963403/159934347-b57faafb-afc4-4ac3-9a9e-b9df4c2e81d6.png)

**Comment by tqbl** [comment]
I can see that `df[key]` is a Series of type int64. Instead of writing `print(value)`, please just enter `value` so I can confirm whether it's an integer or not. Better yet, enter `type(value)`, which will print out the type. If it's a string type, there's your problem. Could you also check that `df.dtypes[key] == int` returns True. If it doesn't, that's likely the source of the bug.

**Comment by The-ultra** [comment]
hey, I just want to thank you for helping me to run this project, moving on
this is the output of putting  `type(value)` 
![image](https://user-images.githubusercontent.com/40963403/160108079-72ad0914-9b49-4073-890b-f97b50ac5aa8.png)

**Comment by tqbl** [comment]
No problem. Alright, we've confirmed that `value` is a string, which is not what we want.

A few lines above the error-causing line, you should see:
```python
# Convert the value to the appropriate type
if df.dtypes[key] == int:
    value = int(value)
```

As I said before, you should check whether `df.dtypes[key] == int` is True or not. I'll save you the trouble and say that it's _not_ True, which is why `value` isn't being converted into an int.

The solution? Well, I have a feeling you're not using the exact same dependency versions, namely pandas 0.25.3. If not, installing that version would be one way to fix it. Always go with the recommended package versions first to avoid headaches. Even in a conda environment, you can do `pip install -r requirements.txt`.

At this point, though, the better solution would be to change that chunk of code to this instead:
```python
if pd.api.types.is_integer_dtype(df.dtypes[key]):
    value = int(value)
```
Make sure you import pandas (as pd).

**Comment by The-ultra** [comment]
it worked, Thank you so much <3
